development:
  FACEBOOK_APP_ID: <%= Figaro.env.FACEBOOK_APP_ID %>
  FACEBOOK_APP_SECRET: <%= Figaro.env.FACEBOOK_APP_SECRET %>
  GOOGLE_OAUTH2_APP_ID: <%= Figaro.env.GOOGLE_OAUTH2_APP_ID %>
  GOOGLE_OAUTH2_APP_SECRET: <%= Figaro.env.GOOGLE_OAUTH2_APP_SECRET %>
